name: fast_localization
description: Fast localization solution for flutter apps using Dart's `Map`
version: 1.0.0
homepage: https://github.com/HasanAlyazidi/fast_localization

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.5
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: